### ISSUE TITLE
2022. 11. 29

### ISSUE THREAD

**Issue by aihoshistar** [to1step/to1step.github.io#1]
- open API 설명 추가 
 - figma 화면 구성 추가 
 - 에디터 설정 추가 
 - tslint 대안? 추가

**Comment by aihoshistar** [comment]
디자이너한테 베스트 컬러 5개 받아오기 .

**Comment by IZGlassy** [comment]
아래 3가지 옵션 중 `git config pull.ff only` 만 사용 하도록 함

```
   git config pull.rebase false  # merge
   git config pull.rebase true   # rebase
   git config pull.ff only       # fast-forward only
```

git pull 이 안될 경우, 대상 Branch 삭제하고 다시 checkout 해서 로컬 remote 업데이트

**Comment by aihoshistar** [comment]
프로젝트 규칙? 개발 문화? 에 대한 메뉴 생성 
 - 클론받기 
 - 개발환경 세팅하기 (extension) 
 - 브런치 네이밍, 커밋 규칙, push, rebase 하기 
 - PR 작성하게 
 - 사용자 리뷰하기

**Comment by aihoshistar** [comment]
개발 팁에 대한 메뉴 
 - CORS 문제, 우회 방법
 - CSR, SSR 
 - 크롬 개발자도구 제대로 사용하기 
 - 리버싱하기

**Comment by aihoshistar** [comment]
교양 
 - 구글 메니저, 애널리틱스 
 - 리캡챠

**Comment by aihoshistar** [comment]
페이지는 추가 했으니, 내용 추가하면 됨
